packages:
  - name: kubernetes/kubernetes/kube-proxy@v1.35.0
  - name: kubernetes/kubernetes/kube-proxy
    version: v1.25.4
  - name: kubernetes/kubernetes/kube-proxy
    version: v1.15.3
  - name: kubernetes/kubernetes/kube-proxy
    version: v1.2.7
