packages:
  - type: github_release
    repo_owner: kubernetes
    repo_name: kops
    description: Kubernetes Operations (kops) - Production Grade K8s Installation, Upgrades, and Management
    complete_windows_ext: false
    supported_envs: ["darwin", "linux", "windows/amd64"]
    asset: "kops-{{.OS}}-{{.Arch}}"
