packages:
  - name: kubernetes/kubernetes/apiextensions-apiserver@v1.35.1
  - name: kubernetes/kubernetes/apiextensions-apiserver
    version: v1.25.4
  - name: kubernetes/kubernetes/apiextensions-apiserver
    version: v1.15.3
