packages:
  - type: github_release
    repo_owner: grafana
    repo_name: grizzly
    asset: grr-{{.OS}}-{{.Arch}}
    description: A utility for managing Jsonnet dashboards against the Grafana API
    supported_envs:
      - darwin
      - linux
    files:
      - name: grr
