packages:
  - name: kubernetes/kubernetes/kubectl-convert@v1.35.1
  - name: kubernetes/kubernetes/kubectl-convert
    version: v1.25.4
  - name: kubernetes/kubernetes/kubectl-convert
    version: v1.22.17
