packages:
  - name: kubernetes/kubectl-convert@v1.31.0
  - name: kubernetes/kubectl-convert
    version: v1.24.7
  - name: kubernetes/kubectl-convert
    version: v1.23.13
  - name: kubernetes/kubectl-convert
    version: v1.22.15
