packages:
  - name: kubernetes/kubeadm@v1.25.10
  - name: kubernetes/kubeadm
    version: v1.24.7
  - name: kubernetes/kubeadm
    version: v1.23.13
  - name: kubernetes/kubeadm
    version: v1.22.15
