# yaml-language-server: $schema=https://raw.githubusercontent.com/aquaproj/aqua/main/json-schema/registry.json
packages:
  - name: kubernetes/cloud-provider-gcp/gke-gcloud-auth-plugin
    type: github_release
    repo_owner: kubernetes
    repo_name: cloud-provider-gcp
    description: cloud-provider-gcp contains several projects used to run Kubernetes in Google Cloud
