packages:
  - name: kubernetes/kubernetes/kubelet@v1.35.1
  - name: kubernetes/kubernetes/kubelet
    version: v1.25.4
  - name: kubernetes/kubernetes/kubelet
    version: v1.15.3
  - name: kubernetes/kubernetes/kubelet
    version: v1.2.7
