---
name: actionlint
env:
  AQUA_LOG_COLOR: always
on:
  push:
    branches: [main]
    paths:
      - .github/**
  pull_request:
    branches: [main]
    paths:
      - .github/**
permissions: {}
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
      - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        with:
          aqua_version: v2.3.5
          policy_allow: "true"
      - run: actionlint -ignore "duplicate value"
