---
name: Check files
permissions: {}
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/check-files.yaml
      - pkgs/**/pkg.yaml
      - pkgs/**/registry.yaml
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/check-files.yaml
      - pkgs/**/pkg.yaml
      - pkgs/**/registry.yaml
jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: aquaproj/registry-action/check-files@39773065a44549758440b90a9e25f713c7e1db34 # tag=v0.1.4
