---
name: Debug with action-tmate
on:
  workflow_dispatch:
    inputs:
      runs-on:
        required: false
        default: windows-latest
      pr_number:
        required: false
      ref:
        required: false
jobs:
  action-tmate:
    runs-on: ${{inputs.runs-on}}
    timeout-minutes: 360
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{inputs.ref}}
          persist-credentials: false

      - run: gh pr checkout "${{inputs.pr_number}}"
        if: inputs.pr_number != ''
        env:
          GITHUB_TOKEN: ${{github.token}}
      - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.43.0
          policy_allow: "true"
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      # The default vim doesn't work well, so we install the latest vim ourselves.
      - uses: rhysd/action-setup-vim@5e3e36ccff48d46653791489d7bf1096e2c2e9f9 # v1.4.0

      - uses: mxschmitt/action-tmate@1005f9c9db5f1b055a495e72c6e589764984baf6 # v3.14
        with:
          limit-access-to-actor: true # SSH Key is required
        env:
          GITHUB_TOKEN: ${{github.token}} # Pass GitHub Token to shell session
