---
name: Release
on:
  push:
    tags: ["*"]
permissions:
  contents: write # required to create a release
  id-token: write # required for cosign
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - name: Install Cosign
        uses: aquaproj/aqua-installer@c553e04154f1f3b7e5eb35da058db3bb782bee8a # tag=v1.1.2
        with:
          aqua_version: v1.25.0
      - name: Sign aqua-registry with Cosign
        run: |
          cosign sign-blob \
            --output-signature registry.yaml.sig \
            --output-certificate registry.yaml.pem \
            --oidc-provider github \
            registry.yaml
        env:
          COSIGN_EXPERIMENTAL: "1"
      - name: Create a draft release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          draft: true
          files: |
            registry.yaml.sig
            registry.yaml.pem
