---
name: Update packages by aqua-registry-updater
on: workflow_dispatch

env:
  AQUA_GLOBAL_CONFIG: ${{ github.workspace }}/aqua-all.yaml
  AQUA_LOG_COLOR: always

permissions: {}

jobs:
  update-pkgs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        with:
          aqua_version: v2.8.0
          policy_allow: "true"
          aqua_opts: -l -a
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: git config user.name "Shunsuke Suzuki"
      - run: git config user.email "suzuki.shunsuke.1989@gmail.com"
      - run: gh auth login
        env:
          GH_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      - run: aqua-registry-updater
        env:
          # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
          # GitHub Packages only supports authentication using a personal access token (classic).
          GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
