---
name: Update packages by aqua-registry-updater
on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/10 * * * *"

env:
  AQUA_GLOBAL_CONFIG: ${{ github.workspace }}/aqua-all.yaml
  AQUA_LOG_COLOR: always

jobs:
  update-pkgs:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: aquaproj/aqua-installer@36dc5833b04eb63f06e3bb818aa6b7a6e6db99a9 # v2.1.2
        with:
          aqua_version: v2.11.0-4
          policy_allow: "true"
          aqua_opts: -l -a
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        with:
          app_id: ${{secrets.APP_ID}}
          private_key: ${{secrets.APP_PRIVATE_KEY}}
      - run: aqua-registry-updater
        env:
          AQUA_REGISTRY_UPDATER_CONTAINER_REGISTRY_TOKEN: ${{github.token}}
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
