---
name: wc-lintnet
on: workflow_call
env:
  AQUA_LOG_COLOR: always
jobs:
  lintnet:
    runs-on: ubuntu-latest
    env:
      AQUA_CONFIG: aqua-all.yaml
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.37.0-2
          policy_allow: "true"
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - run: lintnet lint
        env:
          GITHUB_TOKEN: ${{github.token}}
