---
name: wc-lintnet
on: workflow_call
env:
  AQUA_LOG_COLOR: always
jobs:
  lintnet:
    runs-on: ubuntu-latest
    env:
      AQUA_CONFIG: aqua-all.yaml
    permissions: {}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.34.0
          policy_allow: "true"
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}

      - run: lintnet lint
        env:
          GITHUB_TOKEN: ${{github.token}}
