---
name: test-docker
on: workflow_call
jobs:
  test-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
        with:
          aqua_version: v2.37.0
          policy_allow: "true"
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - name: test GitHub Release
        run: cmdx t suzuki-shunsuke/mkghtag
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      # # Stop testing cargo package as this step takes a long time
      # - name: test cargo package
      #   run: cmdx t bensadeh/tailspin
      #   env:
      #     AQUA_GITHUB_TOKEN: ${{github.token}}
