---
name: test-docker
on: workflow_call
jobs:
  test-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
        with:
          aqua_version: v2.45.0-4
          policy_allow: "true"
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - name: test GitHub Release
        run: cmdx t suzuki-shunsuke/mkghtag
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      # # Stop testing cargo package as this step takes a long time
      # - name: test cargo package
      #   run: cmdx t bensadeh/tailspin
      #   env:
      #     AQUA_GITHUB_TOKEN: ${{github.token}}
